package face

// Sprite grids: 16 columns x 12 rows per frame, transcribed verbatim from
// docs/design/SPRITES.md. Frame B is kept as a full grid (not a diff over
// Frame A) so Render never needs a merge step.
const (
	spriteWidth  = 16
	spriteHeight = 12
	frameA       = 0
	frameB       = 1
)

// palette256 maps a sprite glyph to its ANSI 256-color code. '.' (transparent)
// deliberately has no entry.
var palette256 = map[byte]int{
	'k': 238,
	'c': 230,
	'd': 179,
	'y': 220,
	'Y': 227,
	'o': 208,
	'b': 39,
	'B': 25,
	'g': 77,
	'p': 211,
	'*': 228,
}

// sprites[stage][frame] is a 12-row grid of 16-char strings.
var sprites = [StagePartner + 1][2][spriteHeight]string{
	StageEgg: {
		{
			"................",
			"................",
			"................",
			"......kkkk......",
			".....kcccck.....",
			"....kcccccck....",
			"....kcdcccck....",
			"...kccdccccck...",
			"...kccccccdck...",
			"...kcccccccck...",
			"....kcccccck....",
			".....kkkkkk.....",
		},
		{
			"................",
			"................",
			"................",
			".......kkkk.....",
			"......kcccck....",
			".....kcccccck...",
			".....kcdcccck...",
			"...kccdccccck...",
			"...kccccccdck...",
			"...kcccccccck...",
			"....kcccccck....",
			".....kkkkkk.....",
		},
	},
	StageChick: {
		{
			"................",
			"................",
			"......kkkk......",
			".....kyyyyk.....",
			"....kyyyyyyk....",
			"....kykyykyk....",
			"....kyyooyyk....",
			"...kyyyyyyyyk...",
			"...kcycyycyck...",
			"...kcccccccck...",
			"....kcccccck....",
			".....kkkkkk.....",
		},
		{
			"................",
			"................",
			"......kkkk......",
			".....kyyyyk.....",
			"....kyyyyyyk....",
			"....kyyyyyyk....",
			"....kykookyk....",
			"...kyyyyyyyyk...",
			"...kcycyycyck...",
			"...kcccccccck...",
			"....kcccccck....",
			".....kkkkkk.....",
		},
	},
	StageChild: {
		{
			"................",
			"................",
			"......kkkk......",
			".....kyyyyk.....",
			"....kyyyyyyk....",
			"....kykyykyk....",
			"....kyyooyyk....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kyyyyyyyyk...",
			"....kyyyyyyk....",
			".....oo..oo.....",
		},
		{
			"................",
			"................",
			"......kkkk......",
			".....kyyyyk.....",
			"....kyyyyyyk....",
			"....kyyyyyyk....",
			"....kykookyk....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kyyyyyyyyk...",
			"....kyyyyyyk....",
			".....oo..oo.....",
		},
	},
	StageYouth: {
		{
			"........g.......",
			".......g........",
			".....kkkkkk.....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kykyyyykyk...",
			"...kyyyooyyyk...",
			"..kykyyyyyykyk..",
			"..kykyyyyyykyk..",
			"..kyyyyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
		{
			".......g........",
			"........g.......",
			".....kkkkkk.....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kyyyyyyyyk...",
			"...kykyooykyk...",
			"..kykyyyyyykyk..",
			"..kykyyyyyykyk..",
			"..kyyyyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
	},
	StageAdult: {
		{
			"........g.......",
			".......g........",
			".....kkkkkk.....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kykyyyykyk...",
			"...kyyyooyyyk...",
			".kbbbbbbbbbbbbk.",
			"..kybByyyyyyyk..",
			"..kybyyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
		{
			".......g........",
			"........g.......",
			".....kkkkkk.....",
			"....kyyyyyyk....",
			"...kyyyyyyyyk...",
			"...kyyyyyyyyk...",
			"...kykyooykyk...",
			".kbbbbbbbbbbbbk.",
			"..kybByyyyyyyk..",
			"..kyybyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
	},
	StagePartner: {
		{
			"..*.....g.......",
			".......g......*.",
			".....kkkkkk.....",
			"....kyYYyyyk....",
			"...kyyyyyyyyk...",
			"...kykyyyykyk...",
			"...kpyyooyypk...",
			".kbbbbbbbbbbbbk.",
			"..kybByyyyyyyk..",
			"..kybyyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
		{
			"........g....*..",
			"..*....g........",
			".....kkkkkk.....",
			"....kyYYyyyk....",
			"...kyyyyyyyyk...",
			"...kyyyyyyyyk...",
			"...kpkyooykpk...",
			".kbbbbbbbbbbbbk.",
			"..kybByyyyyyyk..",
			"..kyybyyyyyyyk..",
			"...kyyyyyyyyk...",
			"....oo....oo....",
		},
	},
}
