package face

// Sprite grids: 16 columns x 12 rows per frame, transcribed verbatim from
// docs/design/SPRITES.md (v2 — 柴犬・斜めポーズ). Frame B is kept as a full
// grid (not a diff over Frame A) so Render never needs a merge step.
const (
	spriteWidth  = 16
	spriteHeight = 12
	frameA       = 0
	frameB       = 1
)

// palette256 maps a sprite glyph to its ANSI 256-color code — the terminal
// projection of the window renderer's grayscale six (the mapping table
// lives in SPRITES.md). '.' (transparent) deliberately has no entry.
var palette256 = map[byte]int{
	'k': 236,
	'e': 234,
	'W': 231,
	'l': 253,
	'm': 248,
	'd': 241,
}

// sprites[stage][frame] is a 12-row grid of 16-char strings.
var sprites = [StagePartner + 1][2][spriteHeight]string{
	StageEgg: {
		{
			"................",
			"................",
			"....kkkkkkkk....",
			"...kllllllllk...",
			"..kllmmllllllk..",
			"..kllllllllllk..",
			"..klllllllmmlk..",
			"..kllllllllllk..",
			"..klmmlllllllk..",
			"..kllllllmmllk..",
			"...kllllllllk...",
			"....kkkkkkkk....",
		},
		{
			"................",
			"................",
			"....kkkkkkkk....",
			"...kllllllllk...",
			"..klmmlllllllk..",
			"..kllllllllllk..",
			"..kllllllllmmk..",
			"..kllllllllllk..",
			"..kllmmllllllk..",
			"..klllllllmmlk..",
			"...kllllllllk...",
			"....kkkkkkkk....",
		},
	},
	StageChick: {
		{
			"................",
			"................",
			"................",
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kmeemeemk.....",
			"..kWWWeWWmk.m...",
			"..kWWWmmmmmkmk..",
			"..kWkWWmmmmmk...",
			"...kkkkkkkkkk...",
		},
		{
			"................",
			"................",
			"................",
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kWWWeWWmk.m...",
			"..kWWWmmmmmkmk..",
			"..kWkWWmmmmmk...",
			"...kkkkkkkkkk...",
		},
	},
	StageChild: {
		{
			"................",
			".......m........",
			"...kk.m.kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			"..kWWWWWmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
		{
			"................",
			".....m..........",
			"...kk.m.kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			"..kWWWWWmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
	},
	StageYouth: {
		{
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			"..kWWWWWmmmmmmk.",
			"..kWWWWmmmmmmmk.",
			"..kWWWWmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
		{
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			"..kWWWWWmmmmmmk.",
			"..kWWWWmmmmmmmk.",
			"..kWWWWmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
	},
	StageAdult: {
		{
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			".kddddddddddmmk.",
			"..kWWdddmmmmmmk.",
			"..kWWWdmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
		{
			"...kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			".kddddddddddmmk.",
			"..kWWdddmmmmmmk.",
			"..kWWWdmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
	},
	StagePartner: {
		{
			"...kk...kk..m...",
			"..kmmk.kmmk.....",
			"m.kmmmmmmmk.....",
			"..kmmmmmmmk.....",
			"..kmeemeemk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			".kddddddddddmmk.",
			"..kWWdddmmmmmmk.",
			"..kWWWdmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
		{
			"m..kk...kk......",
			"..kmmk.kmmk.....",
			"..kmmmmmmmk.....",
			"..kmmmmmmmk.m...",
			"..kmmmmmmmk.....",
			"..kmeemeemk.kk..",
			"..kWWWeWWmkkmmk.",
			".kddddddddddmmk.",
			"..kWWdddmmmmmmk.",
			"..kWWWdmmmmmmmk.",
			"..kWkWWmmmmkmmk.",
			"...kkkkkkkkkkk..",
		},
	},
}
